---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:

- name: ubuntu-14-04-x64
  driver_config:
    size: 8gb
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[openstack-model-t::default]