---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "10.0.0.21"}]
#    - ["public_network", {bridge: "en3: Thunderbolt Ethernet"}]
    - ["public_network", {bridge: "en0: Wi-Fi (AirPort)"}]
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
    - ["forwarded_port", {guest: 443, host: 8443}]
    - ["forwarded_port", {guest: 5000, host: 5000}]
    - ["forwarded_port", {guest: 6080, host: 6080}]
    - ["forwarded_port", {guest: 8773, host: 8773}]
    - ["forwarded_port", {guest: 8774, host: 8774}]
    - ["forwarded_port", {guest: 35357, host: 35357}]
  customize:
    cpus: 4
    memory: 8096
    nicpromisc3: 'allow-all'

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[openstack-model-t::default]
    attributes:
